name: Deploy Infrastructure to AWS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout infrastructure repo
        uses: actions/checkout@v3
        with:
            path: infrastructure
        
      - name: ⬇️ Checkout Core Repo
        uses: actions/checkout@v3
        with:
            repository: findora-nl/core
            path: core
            token: ${{ secrets.CORE_REPO_PAT }}

      - name: 📦 Install and Build Lambda
        working-directory: core
        run: |
          make package

      - name: ⚙️ Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: ☁️ Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: 📂 Terraform Init
        working-directory: infrastructure
        run: terraform init

      - name: 🧪 Terraform Validate
        working-directory: infrastructure
        run: terraform validate

      - name: 📊 Terraform Plan
        working-directory: infrastructure
        run: |
            terraform plan \
            -var="openai_api_key=${{ secrets.OPENAI_API_KEY }}"

      - name: 🚀 Terraform Apply
        working-directory: infrastructure
        run: |
            terraform apply -auto-approve \
            -var="openai_api_key=${{ secrets.OPENAI_API_KEY }}"
